apiVersion: 1

datasources:
  - name: sectel_db
    uid: sectelpg
    type: postgres
    access: proxy
    url: localhost:5432
    user: postgres
    database: sectel_db
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: postgres
